# Generated by Django 3.1 on 2020-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('checkedOutBy', models.CharField(max_length=100)),
                ('checkOutDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
