# Generated by Django 3.1 on 2020-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200809_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkOutDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkedOutBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('checkedOut', 'Checked Out'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('digitalCopy', 'Digital Copy')], default='available', max_length=30),
        ),
    ]
